### ISSUE TITLE
Unable to access documentation.

### ISSUE THREAD

**Issue by KevinBurton** [thingdom/node-neo4j#118]
If I click on 'API Documentation' or the Docs link on the Neo4j web site I get:

Oops! Google Chrome could not find coffeedoc.info
Access a cached copy of coffeedoc.­info/­github/­thingdom/­node-­neo4j/­master/­

**Comment by ankursmooth** [comment]
http://downforeveryoneorjustme.com/http://coffeedoc.info/github/thingdom/node-neo4j/master/ this says It's not just you! http://coffeedoc.info looks down from here.
can document pages also be hosted on github?
