### ISSUE TITLE
HTTP Basic Auth extension management APIs

### ISSUE THREAD

**Issue by sheymann** [thingdom/node-neo4j#126]
*Title edited by @aseemk. The original title was "HTTP Basic Authentication handler is incomplete".*

—

in GraphDatabase constructor(opts):

```
@option opts url {String} The root URL where the Neo4j graph database
    #     is available, e.g. `'http://localhost:7474/'`. This URL should
    #     include HTTP Basic Authentication info if needed, e.g.
    #     `'http://user:password@example.com/'`.
```

is incomplete, see https://github.com/neo4j-contrib/authentication-extension

The constructor should send a POST request to the Neo4j http://server:port/auth endpoint.

**Comment by aseemk** [comment]
Neo4j 2.2 will ship with a native auth mechanism. It won't have the ability to manage multiple users, etc. yet, so do you see yourself still using the Auth extension?

Also, Neo4j v2 (almost ready, but available on npm; the latest version is `2.0.0-alpha3`; [docs](https://github.com/thingdom/node-neo4j/blob/v2/API_v2.md#schema)) adds a custom `GraphDatabase::http` method to make arbitrary HTTP requests to Neo4j's REST API (#100), so you can now talk to custom plugins freely.

Given both these things, I think/hope it's okay to close this. Thanks again @sheymann!
