### ISSUE TITLE
How to parameterize relationship in Cypher query?

### ISSUE THREAD

**Issue by kdekooter** [thingdom/node-neo4j#147]
I tried to execute this query:

```
MATCH (from:Company), (to:Company)
WHERE from.id = {fromId} AND to.id = {toId}
CREATE from-[:{relationship}]->to
```
The parameters are:
```
{
  "from": 29,
  "to": 30,
  "type": "SUPPLIER"
}
```
However Neo4J does not accept this:
```
Invalid input '{': expected whitespace or a rel type name (line 3, column 22)
```
Is it at all possible to parameterize the relationship?

**Comment by aseemk** [comment]
Sorry for the delay!

Looking at <http://neo4j.com/docs/stable/cypher-parameters.html>, it appears not (emphasis mine):

> Parameters can not be used as for property names, **relationship types** and labels, since these patterns are part of the query structure that is compiled into a query plan.

So you'll have to include that directly in the query, e.g. via string concatenation or similar.

Hope that helps!
