### ISSUE TITLE
The reference url for API documentation doesn't work!

### ISSUE THREAD

**Issue by nikolay211** [thingdom/node-neo4j#148]
Hi 

I'm planning to use neo4j db in my new project and woud like to use this api wrapper in our project as well. 

I'd like to skim through your API reference but unfortunately the site seems to be not working.

Any help?

**Comment by aseemk** [comment]
Oh, thanks for the heads-up. I'm not sure why that is, but I let the provider know:

https://github.com/coffeedoc/codo/issues/192

Hopefully this is just a temporary hiccup and it's back up soon. If not, I'll look into alternative hosting. (The nice thing about that service though is it auto-updates on pushes of new commits.)

In the meantime, a couple of options you have for browsing the docs are:

- You can always view the source directly. The docs are generated from inline comments. =)

- Clone the repo locally and simply run `npm install && npm run codo`.

Thanks again, and hope that helps for now!

**Comment by aseemk** [comment]
Okay, looks like it's back. Thanks again for reporting, @nikolay211.
