### ISSUE TITLE
Error message Object #<GraphDatabase> has no method 'createNode'

### ISSUE THREAD

**Issue by Christopheraburns** [thingdom/node-neo4j#150]
Hello all, very sorry to ask a support type question here but I am running out of options.  I have the following TWO lines of code in my node.js project 

 var db = new neo4j.GraphDatabase('http://localhost:7474');
 var node = db.createNode({ hello: 'world' });

There is indeed a local instance of neo4j (version 2.1.7) up and running.  However, I get the error message in the subject line above when attempting to execute the code.  I am new to Node.js so this has been a long winding road and getting this data written to neo4j is the last piece of the puzzle.  Any help would be appreciated.

**Comment by aseemk** [comment]
Hi @Christopheraburns! Run this for me:

```sh
npm ls neo4j
```

I'm guessing you've installed node-neo4j v2 (we have alpha versions in npm currently), which has breaking changes to the API. The output of that `npm ls` will tell you if you have node-neo4j v1 or v2 installed (e.g. `1.1.1` vs. `2.0.0-alpha3`).

You can downgrade to `1.1.1` by doing:

```sh
npm uninstall neo4j
npm install neo4j@1.1.1 --save
```

Alternately, if you're interested in v2 (still a WIP! but almost finished, and pretty stable), here are some temporary links until this gets merged to master:

API docs (WIP): https://github.com/thingdom/node-neo4j/blob/v2/API_v2.md
Readme (WIP): https://github.com/thingdom/node-neo4j/tree/v2#readme
Pull request: https://github.com/thingdom/node-neo4j/pull/145

Hope this helps! Feel free to re-open if this doesn't resolve things for you.

**Comment by Christopheraburns** [comment]
Perfect, that was it!  While I am here, I will press my luck and add one more quick question.  I don't see the ability to create a label when creating the node (using version 1.1.1). Is there perhaps support for passing entire cypher queries in json?  Thank you very much for your help.

**Comment by aseemk** [comment]
Yes, and yes! See the node-neo4j-template app, specifically these lines:

https://github.com/aseemk/node-neo4j-template/blob/master/models/user.js#L162-L163
