### ISSUE TITLE
Async connection w/callback

### ISSUE THREAD

**Issue by MaxwellRebo** [thingdom/node-neo4j#155]
It'd be great if the connection was asynchronous with a callback - is this part of V2?

**Comment by aseemk** [comment]
Neo4j's API actually doesn't require any initial connection, so there isn't any synchronous connection or anything like that today. The API is just a standard REST one, over HTTP, so a connection/request is only made when you execute a query. (Under the hood, the connection is Keep-Alive for perf, although I need to update this for Node 0.12, I think.)

Does that clarify? Or am I misunderstanding your request?

**Comment by MaxwellRebo** [comment]
Yes, that makes perfect sense. Thanks for the reply.

For my use case, I just needed a way to ensure the connection is good before initializing other modules. What I ended up doing was wrapping the initialization with promises, doing a quick write then delete operation to ensure the connection is good. This works just fine.

Thanks!

**Comment by aseemk** [comment]
Great. :+1: 

FYI that if you just want to test the connection, a simple read query will suffice; no need to do two writes instead (unless there's something more that I'm missing).

In fact, if you *just8 care that the connection is good, and can trust that the db is fine if you can connect to it (which in most cases would be reasonable), you can just do a simple query like `RETURN true` for optimal efficiency (no need to touch any nodes, and O(1)).
