### ISSUE TITLE
simple insert not working on GrapheneDB 

### ISSUE THREAD

**Issue by pranavpunjabi** [thingdom/node-neo4j#157]
I have a remote db hosted on GrapheneDB. I am trying to insert a node into my db.

```javascript
var neo4j = require("neo4j");
var db = new neo4j.GraphDatabase("http://user:password@ompdb.sb05.stations.graphenedb.com:24789");


var node = db.createNode({hello: 'world'});    
node.save(function (err, node) {    
    if (err) {
        console.error('Error saving new node to database:', err);
    } else {
        console.log('Node saved to database with id:', node.id);
    }
});
```

On execution, I get a 500 error.
Am I using this driver correctly?

**Comment by aseemk** [comment]
Yes, your usage looks correct. What's the 500 error message? That suggests a GrapheneDB issue rather than a node-neo4j one, but the error message should be able to confirm.

**Comment by Khaled-h-aly** [comment]
I am doing the same connection but I have an "Uncaught Error: Module name "neo4j" has not been loaded yet for context: _. Use require([])".
I am loading the require.js using <script> in the index.html file and them loading the service.js file.
Sorry, this is all new for me.
