### ISSUE TITLE
Is there a way to get the query that is being executed?

### ISSUE THREAD

**Issue by swarajgiri** [thingdom/node-neo4j#162]

**Comment by aseemk** [comment]
There isn't today, but you could easily achieve that yourself, by adding a helper function in front of node-neo4j calls. E.g. (assuming you're using node-neo4j v2):

```js
// map from query to itself, effectively a set:
var queries = {};

function cypher(query, params, callback) {
    // save this query as running:
    queries[query] = query;
    // then execute the query:
    db.cypher({query: query, params: params}, function (err, results) {
        // finally, remove the query:
        delete queries[query];
        // before forwarding the results:
        callback(err, results);
    }
}
```

Now `queries` contains all the currently running queries.

Hope that helps! Feel free to re-open if I misunderstood or if you have any more q's.

**Comment by swarajgiri** [comment]
Sorry for not being clear enough.
What i needed was a way to get the query that is being generated after the params are substituted with the passed values.

**Comment by aseemk** [comment]
Oh, there is no parameter substitution or new query generation. The parameters are sent *alongside* the query, and used by Neo4j directly. This is how you avoid injection attacks.

http://neo4j.com/docs/stable/cypher-parameters.html

Hope that helps?
