### ISSUE TITLE
Using params in regex passes through to neo4j

### ISSUE THREAD

**Issue by richardwillars** [thingdom/node-neo4j#167]
Using the following query:
`MATCH (f:Foo) WHERE f.name =~ '.*{name}.*' RETURN f LIMIT 100`

Which when executed with 
```
var fields = { name: 'bar' };
db.cypher({ query: query, params: fields })
```

Throws up an error:
>    { [neo4j.DatabaseError: [Neo.DatabaseError.Statement.ExecutionFailure] java.util.regex.PatternSyntaxException: Illegal repetition near index 1
    .*{name}.*

It looks like it's passing the parameter name with the curly braces through the library to neo4j. Should it scan for parameters and inject them into the query like it does with strings etc? If not, what is the best practice for building regular expressions based on user input?

**Comment by aseemk** [comment]
Hey @richardwillars, I'm not 100% sure (cc @jexp?), but I think params are all-or-nothing, so if you want to use a regex value, it has to be the param.

So try:

```cypher
MATCH (f:Foo) WHERE f.name =~ {name} RETURN f LIMIT 100
```

```js
var fields = { name: '.*bar.*' };
db.cypher({ query: query, params: fields })
```

**Comment by richardwillars** [comment]
Damn, that was too easy! Works fine and is quite logical really.. probably just needs adding to the documentation more than anything.

Thanks

**Comment by aseemk** [comment]
Great. Okay, will keep it in mind for node-neo4j documentation, but cc @jexp for Cypher docs too. =)

**Comment by jexp** [comment]
You can also use

a.name =~ '.*'+{name}+'.*'

Von meinem iPhone gesendet

**Comment by fabianTMC** [comment]
Please add this to the documentation.
