### ISSUE TITLE
High Availability support

### ISSUE THREAD

**Issue by ScOut3R** [thingdom/node-neo4j#169]
Hi,

I am new to Neo4j so please forgive if I am speaking nonsense here. :) Does the client have to support HA if it uses the REST API? The official documentation recommends a load balancer in front of a Neo4j cluster so the client just has to connect to one endpoint and the load balancers will take of the rest. Can this library used in this way?

Kind regards,
Mate

**Comment by aseemk** [comment]
Hi @ScOut3R, sorry for the delay in responding! I was off the grid for a bit. =)

You have it exactly right. And coincidentally, I just wrote up the documentation on that for v2:

https://github.com/thingdom/node-neo4j/tree/v2#high-availability

Cheers,
Aseem
