### ISSUE TITLE
what is the default password?  it is not 'neo4j'

### ISSUE THREAD

**Issue by pangguoming** [thingdom/node-neo4j#173]
i try to login wiht user: neo4j  passwod: neo4j 
it say: Invalid username or password.

**Comment by hilkeheremans** [comment]
Can you try logging into Neo4j's web interface first? It will then prompt you to change the password.

(I'm assuming here that Neo4j does not allow remote connections to the REST api as long as the password has not been changed. Not sure if that holds true.)

**Comment by divmgl** [comment]
This question isn't relevant to `node-neo4j`. https://github.com/neo4j/neo4j/issues

If it's not working for you, you've already changed the password. Reinstall neo4j.

**Comment by pangguoming** [comment]
Thanks , I solved the problem already
