### ISSUE TITLE
Unable to connect to Neo4j 2.2.5 community edition, no errors thrown.

### ISSUE THREAD

**Issue by MaxYari** [thingdom/node-neo4j#174]
Hello fellow coders! 
Honestly i'm just feeling stupid asking this, .. bit i'm stuck at the mere beginning!
I'm running `Neo4j 2.2.5 community edition` on `windows 8`, I can access neo4j's awesome browser interface on `http://localhost:7474` and now i'm trying to connect from node:
        
        var neo = new neo4j.GraphDatabase({
	    url: 'http://localhost:7474',
	    auth: {username: 'neo4j', password: '***'}    
	});

But nothing is happening, complete silence! Even if i change url or username/password to some random thing... 
Console.log of `neo` shows this:

     { reviveJSON: [Function],
           url: 'http://localhost:7474',
           _request:
            { get: [Function],
              post: [Function],
              put: [Function],
              del: [Function],
              head: [Function] },
     _root: null,
     _services: null }

So running `neo.cypher` for example obvoiusly throws undefined... what am I missing?

**Comment by aseemk** [comment]
Hi @MaxYari,

It sounds like you're running node-neo4j v1, when you want to be running node-neo4j v2. =)

Try `npm uninstall neo4j && npm install neo4j@2.0.0-RC2`. Does that work?

Sorry, I realize the v2 readme doesn't make this clear. Will fix. Thanks!

**Comment by lineves** [comment]
Same thing happened to me, and solved now ~ 

Were this message been in the readme.md's installation section.

**Comment by MaxYari** [comment]
@aseemk I was trying everything to get neo4j going asap that day so i just migrated to seraph =)
But yep, it seems that was the reason why my node-neo4j was silently failing, thank You!
