### ISSUE TITLE
when i use 'node-neo4j ', should i ensure there are only one 'GraphDatabase' instance ?

### ISSUE THREAD

**Issue by pangguoming** [thingdom/node-neo4j#175]
when i use 'node-neo4j ', should i ensure there are only one 'GraphDatabase' instance ?
In other words,  the following code should run just once ?
var db = new neo4j.GraphDatabase(...);

**Comment by aseemk** [comment]
With node-neo4j v1: yes, you should ensure only one GraphDatabase instance.
With node-neo4j v2: no harm in multiple GraphDatabase instances. =)

Hope this helps!

**Comment by aseemk** [comment]
For a bit more detail:

- v1 was hypermedia-driven, so a new GraphDatabase instance would make some round-trip network requests to "discover" the API. Multiple instances, then, isn't efficient.

- v2 is stateless, functional, and no longer hypermedia-driven. So multiple instances isn't harmful.
