### ISSUE TITLE
Dose Transaction support Http POST\GET method?

### ISSUE THREAD

**Issue by pangguoming** [thingdom/node-neo4j#180]
when do something like : 
var tx = db.beginTransaction();
tx.http({
    method: 'GET',
    path: "/db/data",
    body: {
    }
}, finish);

i get error: tx.http({
   ^
TypeError: undefined is not a function

**Comment by aseemk** [comment]
Nope, transactions only support Cypher queries. This is a Neo4j limitation, not unique to this driver.

**Comment by pangguoming** [comment]
ok, i got it ,thanks
