### ISSUE TITLE
Documentation is not opening 

### ISSUE THREAD

**Issue by nishantt12** [thingdom/node-neo4j#193]
Api Documentation url is working : - http://coffeedoc.info/github/thingdom/node-neo4j/master/

I need documentation, can you tell me how can i get that ?

**Comment by aseemk** [comment]
That third-party hosted site seems to be down, unfortunately, but the good news is:

- That's only the documentation for v1. If you're using v2, the docs are the v2 [readme](https://github.com/thingdom/node-neo4j/tree/v2#readme) and the v2 [spec](https://github.com/thingdom/node-neo4j/blob/v2/API_v2.md).

- If you _are_ on v1, you can generate the documentation yourself locally by going into your `node_modules/neo4j` folder, running `npm install` and then `npm run codo`.

Hope that helps!
