### ISSUE TITLE
Create DataBase Neo4j with node js

### ISSUE THREAD

**Issue by rezguiHamza** [thingdom/node-neo4j#205]
i have a problem to create a db neoj, this my code in my file server.js:

var db = require("seraph")({
      server: "http://127.0.0.1:7474",
      endpoint: "data/graph.db",
     user: "neo4j",
    pass: "neo4j"
      })
  , graph = require("neo4jquery").setConnection(db)

  , query = "CREATE (vous:Personne { nom:'Vous' })RETURN vous" ;

  graph.Query(query, false, function(err, list) {
      if (err) {
       // callback(err, void 0);
          console.log("ERROR Execution" + err);
      } else {
        // some stuff here with list 

    console.log("requete executée !");
        var user = list[0];
      }
    });
if i connect in http://127.0.0.1:7474 : " Invalid username or password."

when i run server.js it shows me : "ERROR ExecutionError: Invalid username or password."

although I added these two line in "neo4j-server.properties" :

org.neo4j.server.credentials=neo4:neo4j org.neo4j.server.thirdparty_jaxrs_classes=org.neo4j.server.extension.auth=/auth

**Comment by aseemk** [comment]
Hi @rezguiHamza,

It looks like you're using a different driver. Here's the repo for that driver:

https://github.com/brikteknologier/seraph

You might try asking your question over there. Good luck!

**Comment by rezguiHamza** [comment]
Hi @aseemk,
ok , thanks,
