### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by corysimmons** [thingdom/node-neo4j#218]
Last commit Aug 2016. Not crying, just curious if dev is going on somewhere else or if you plan to come back?

**Comment by jyounus** [comment]
Looks like the development on this is dead. :/

**Comment by aseemk** [comment]
Yes, sorry! I haven't been actively working with Neo4j for the past couple of years now, and Neo4j 3.0 (which comes with an official first-party JS driver now) obviated the need for this driver, so development on this driver has stopped. Thank you for your understanding!

**Comment by dbohdan** [comment]
>Neo4j 3.0 (which comes with an official first-party JS driver now) obviated the need for this driver

Thanks for your clarification! Could you add a note saying this to the README?

**Comment by aseemk** [comment]
Done! Thanks for the nudge. Cheers. =)

**Comment by corysimmons** [comment]
Not a problem. Thanks for the honest update and tweak to the README. 👌
